spring:
  data:
    mongodb:
      database: Student
      uri: mongodb+srv://deepak:1234sonu@cluster0.fvcgi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true

server:
  port: 8085

#logging:
#  level:
#    root: off
